### ISSUE TITLE
Please make backport latest version of spark and fix things in todo list

### ISSUE THREAD

**Issue by leonpano2006** [fonnymunkey/spark#5]
last time this mod get upgraded is 2023
spark have updated by time being and open profiler while running is never fixed in to do list

**Comment by fonnymunkey** [comment]
There have been little updates of significance to backport, the majority of updates have only been relevant to newer MC versions, so it is low priority currently.
Live viewer is unlikely to be backported due to it only working on newer Java versions, however if anyone wants to attempt it they are welcome to, this mod is MIT and accepts PRs.

**Comment by leonpano2006** [comment]
Btw can we change builder jdk form
temurin to Azul Zulu?

fonnymunkey ***@***.***>於 2024年5月5日 週日，下午10:22寫道：

**Comment by fonnymunkey** [comment]
As of 1.11.2 all relevant newer updates have been pulled.

If you want to use a different distribution for the build workflow you can change it in your own repository, however I do not see the benefit of changing it, since it does not affect anything besides the initial build of the jar.
